#!/usr/bin/python3
import re
import sys

module     = sys.argv[1]
lang       = sys.argv[2]
msgextract = sys.argv[3]
cpp        = open(sys.argv[5],'w')

print('// Generated by po-cpp-gen.py', file = cpp)
print('#include "arcollect-i18n-'+module+'.hpp"', file = cpp)
print('void Arcollect::i18n::'+module+'::po_apply_'+lang+'(void) noexcept {', file = cpp)

msgctx = None
msgstr = None
def print_msg():
	global msgctx
	global msgstr
	if (msgstr is not None) and (msgstr != '"') and (msgctx is not None):
		print(msgctx,'=',msgstr+'";', file = cpp)
		msgctx = None
		msgstr = None
for line in open(sys.argv[4],'r').readlines():
	command = line.strip().split(' ',1)
	if len(command) > 1:
		string = command[1][1:-1]
	command = command[0]
	if len(command) == 0 or command[0] == '#':
		continue
	elif command[0] == '"':
		if msgstr is not None and msgctx is not None:
			msgstr += string
		continue
	elif command == 'msgctxt':
		print_msg()
		msgctx = string
	elif command == msgextract and msgctx: # Has a msgstr (msgid for C locale)
		msgstr = '"'+string
	else:
		print_msg()
print_msg()
print('}', file = cpp)
