#!/usr/bin/python3
import polib
import re
import sys

module     = sys.argv[1]
lang       = sys.argv[2]
msgextract = sys.argv[3]
pofile     = polib.pofile(sys.argv[4])
cpp        = open(sys.argv[5],'w')

print('// Generated by po-cpp-gen.py', file = cpp)
print('#include "arcollect-i18n-'+module+'.hpp"', file = cpp)
print('void Arcollect::i18n::'+module+'::po_apply_'+lang+'(void) noexcept {', file = cpp)

# Filter-out untranslated entries in non C locale
if msgextract != 'msgid':
	pofile = filter(polib.POEntry.translated,pofile)

for msg in pofile:
	print('\t'+msg.msgctxt,'=','"'+msg.__getattribute__(msgextract).replace('\\','\\\\').replace('\n','\\n').replace('"','\\"')+'";', file = cpp)
print('}', file = cpp)
