#!/usr/bin/python3
import re
import sys

po_in = open(sys.argv[2],'r')
out = open(sys.argv[3],'w')
print('\t\t\t// Generated by po-hpp-gen.py', file = out)

messages = []
for line in po_in.readlines():
	line = line.strip().split(' ',1)
	if len(line) > 1:
		if line[0] == 'msgctxt':
			print('\t\t\tstd::string_view',line[1][1:-1]+';', file = out)
			messages.append(line[1])
print('\t\t\tconstexpr static std::array<std::string_view,'+str(len(messages))+'> po_strings = {',', '.join(messages),'};', file = out)
print('\t\t\tconstexpr const std::string_view get_po_string(const std::string_view& string) const {\n\t\t\t\t', end = '', file = out)
for msg in messages:
	print('if (string ==',msg,') return',msg[1:-1],';\n\t\t\t\telse ', end = '', file = out)
print('return std::string_view();\n\t\t\t}', file = out)
