#!/usr/bin/python3
import polib
import re
import sys

po_in = polib.pofile(sys.argv[2])
out = open(sys.argv[3],'w')
print('\t\t\t// Generated by po-hpp-gen.py', file = out)

messages = list(map(lambda entry: entry.msgctxt, po_in))
for msg in messages:
	print('\t\t\tstd::string_view',msg+';', file = out)
print('\t\t\tconstexpr static std::array<std::string_view,'+str(len(messages))+'> po_strings = {"'+'", "'.join(messages)+'"};', file = out)
print('\t\t\tconstexpr const std::string_view get_po_string(const std::string_view& string) const {\n\t\t\t\t', end = '', file = out)
for msg in messages:
	print('if (string == "'+msg+'") return',msg,';\n\t\t\t\telse ', end = '', file = out)
print('return std::string_view();\n\t\t\t}', file = out)
