#!/bin/sh
. ./script-common.sh

echo "# Generated by packaging/generate-flatpak.sh mode: $1
id: $ARCOLLECT_DBUS_NAME
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
command: arcollect
finish-args:
  # GUI access
  - --socket=wayland
  - --socket=x11
  - --share=ipc  # Allow Xshm
  - --device=dri # Allow OpenGL
modules:
  - name: arcollect
    buildsystem: meson
    sources:"
case "$1" in
	local ) echo "    - type: dir
      path: $(pwd)/..
";;
	release-ci ) echo "    - type: archive
      url: https://github.com/DevilishSpirits/arcollect/archive/refs/tags/v$(arcollect_version).tar.gz
";;
	* ) echo "Wrong mode! Usage:
$0 local      -- Generate a Flatpak YML for end-user local package generation
$0 release-ci -- Generate a Flatpak YML for sharing (for CI only)
" >&2
	exit 1;;
esac
