#!/bin/sh
. ./script-common.sh

echo "# Generated by packaging/generate-PKGBUILD.sh mode: $1
# Maintainer: DevilishSpirits (aka D-Spirits or Luc B.) <devilishspirits@gmail.com>
pkgname=arcollect
pkgver=$(arcollect_version)
pkgrel=1
pkgdesc='$ARCOLLECT_SUMMARY'
arch=('x86_64')
url='$ARCOLLECT_WEBSITE'
license=('GPL')
depends=(xdg-utils brotli dbus 'curl$ARCOLLECT_VERREQ_libcurl' 'fontconfig$ARCOLLECT_VERREQ_fontconfig' 'freetype2$ARCOLLECT_VERREQ_freetype2' 'harfbuzz$ARCOLLECT_VERREQ_harfbuzz' 'lcms2$ARCOLLECT_VERREQ_lcms2' 'sdl2$ARCOLLECT_VERREQ_sdl2' 'sqlite$ARCOLLECT_VERREQ_sqlite3') # TODO Add OpenImageIO when ArchLinux upgrade the version
makedepends=('meson$(meson_version_req)')"

case "$1" in
	local ) arco_srcdir="$(pwd)/.."
	echo "source=()
sha256sums=()
";;
	release-ci ) arco_srcdir='$srcdir/arcollect-$pkgver'
	echo "source=(\"https://github.com/DevilishSpirits/arcollect/archive/refs/tags/v\$pkgver.tar.gz\")
sha256sums=('SKIP')
";;
	* ) echo "Wrong mode! Usage:
$0 local      -- Generate a PKGBUILD for end-user local package generation
$0 release-ci -- Generate a public PKGBUILD for sharing (for CI only)
" >&2
	exit 1;;
esac

echo "
prepare() {
  meson subprojects download --sourcedir \"$arco_srcdir\" oiio robin-map
}

build() {
  arch-meson -Denable_webextension=false \"$arco_srcdir\" build
  meson compile -C build
}

check() {
  meson test -C build --print-errorlogs
}

package() {
  meson install -C build --destdir \"\$pkgdir\"
}"
