#!/usr/bin/python3
# Usage: generate-wix-config 'opt1,opt2,opt...' '/path/to/config.h' 'val1' 'val2' 'val...' > config.wxi
import os
import re
from sys import argv, stdin, stdout

# Configure I/O encoding
stdin.reconfigure(encoding='utf-8')
if 'PYTHONIOENCODING' not in os.environ:
	# Python might use a CP1252 encoding that isn't supported by WiX
	stdout.reconfigure(encoding='utf-8')

# Parse the Meson generated config.h
regex = re.compile('#define ([A-Za-z0-9_]+)_STR (".*")')
print(f"""<?xml version='1.0' encoding='{stdout.encoding}'?>
<Include>
<!-- Auto-generated by packaging/generate-wix-config.py -->""")

print('<!-- From config.h -->')
for line in filter(lambda x:x,map(regex.match,open(argv[2]))):
	print('\t<?define',line.group(1),'=',line.group(2),'?>')

print('<!-- From command-line -->')
for key, value in zip(argv[1].split(','),argv[3:]):
	print('\t<?define',key,'=',value,'?>')
	
print('</Include>')
