if (NOT @JPEG_PREFIX@_FOUND)
	message(NOTICE "Using Arcollect injected JPEGConfig.cmake")
	set(@JPEG_PREFIX@_INCLUDE_DIRS "@JPEG_INCLUDE_DIR@")
	set(@JPEG_PREFIX@_LIBRARY "")
	set(@JPEG_PREFIX@_LIBRARIES "")
	set(@JPEG_PREFIX@_VERSION_STRING "@JPEG_VERSION_STRING@")
	add_library(@JPEG_PREFIX@::@JPEG_PREFIX@ UNKNOWN IMPORTED)
	set_target_properties(@JPEG_PREFIX@::@JPEG_PREFIX@ PROPERTIES
		IMPORTED_LINK_INTERFACE_LANGUAGES "C"
		INTERFACE_INCLUDE_DIRECTORIES "@JPEG_INCLUDE_DIRS@"
		VERSION "@JPEG_VERSION_STRING@"
	)
endif()
