if (NOT TIFF_FOUND)
	message(NOTICE "Using Arcollect injected TIFFConfig.cmake")
	set(TIFF_INCLUDE_DIRS "@TIFF_INCLUDE_DIR@")
	set(TIFF_LIBRARY "@TIFF_LIBRARY@")
	set(TIFF_VERSION "@TIFF_VERSION_STRING@")
	set(TIFF_VERSION_STRING "@TIFF_VERSION_STRING@")
	
	add_library(TIFF::TIFF UNKNOWN IMPORTED)
	set_target_properties(TIFF::TIFF PROPERTIES
		IMPORTED_LOCATION "${TIFF_LIBRARY}"
		IMPORTED_LINK_INTERFACE_LANGUAGES "C"
		INTERFACE_INCLUDE_DIRECTORIES "${TIFF_INCLUDE_DIRS}"
		VERSION "${TIFF_VERSION_STRING}"
	)
endif()
