# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [archlinux]
    steps:
      - uses: actions/checkout@v2
      - name: Recursive checkout
        run: git submodule update --init --recursive
      - name: Build project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: 0.57.1
      - name: Test project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.57.1
      - name: Install project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          meson-version: 0.57.1
        env:
          DESTDIR: "archive-out"
      - name: Archiving
        run: tar -cf archive-out.tar -C build archive-out --transform 's/archive-out//g'
      - name: Uploading DESDIR artifact
        uses: actions/upload-artifact@v2
        with:
          name: install.tar
          path: archive-out.tar
      - name: Uploading arcollect-webextension.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: arcollect-webextension.zip
          path: build/webextension/arcollect.zip
  build-wrapped:
    runs-on: [archlinux]
    steps:
      - uses: actions/checkout@v2
      - name: Recursive checkout
        run: git submodule update --init --recursive
      - name: Build project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-options: --force-fallback-for sqlite
          meson-version: 0.57.1
      - name: Test project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.57.1
      - name: Install project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          meson-version: 0.57.1
        env:
          DESTDIR: "archive-out"
      - name: Archiving
        run: tar -cf archive-out.tar -C build archive-out --transform 's/archive-out//g'
      - name: Uploading DESDIR artifact
        uses: actions/upload-artifact@v2
        with:
          name: install.tar
          path: archive-out.tar
      - name: Uploading arcollect-webextension.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: arcollect-webextension.zip
          path: build/webextension/arcollect.zip
