# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [archlinux]
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: 0.57.1
      - name: Test project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.57.1
      - name: Install project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          meson-version: 0.57.1
        env:
          DESTDIR: "archive-out"
      - name: Archiving
        run: tar -cf archive-out.tar -C build archive-out --transform 's/archive-out//g'
      - name: Uploading DESDIR artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_DESTDIR.tar
          path: archive-out.tar
      - name: Uploading arcollect-webextension.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_webextension.zip
          path: build/webextension/arcollect.zip
  build-wrapped:
    runs-on: [archlinux]
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-options: --force-fallback-for sqlite,sdl2_image,sdl2_ttf
          meson-version: 0.57.1
      - name: Test project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.57.1
      - name: Install project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          meson-version: 0.57.1
        env:
          DESTDIR: "archive-out"
      - name: Archiving
        run: tar -cf archive-out.tar -C build archive-out --transform 's/archive-out//g'
      - name: Uploading DESDIR artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-wrapped_DESTDIR.tar
          path: archive-out.tar
      - name: Uploading arcollect-webextension.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-wrapped_webextension.zip
          path: build/webextension/arcollect.zip
  build-ubuntu-20_04:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2 and his image and ttf modules
        run: sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
      - name: Install Mozilla's web-ext with npm
        run: sudo npm install -g web-ext
      - name: Build project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          meson-version: 0.57.1
      - name: Test project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.57.1
      - name: Install project
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          meson-version: 0.57.1
        env:
          DESTDIR: "archive-out"
      - name: Archiving
        run: tar -cf archive-out.tar -C build archive-out --transform 's/archive-out//g'
      - name: Uploading DESDIR artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-20_04_DESTDIR.tar
          path: archive-out.tar
      - name: Uploading arcollect-webextension.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-20_04_webextension.zip
          path: build/webextension/arcollect.zip
  check-webextensions-same:
    needs: [build, build-wrapped, build-ubuntu-20_04]
    runs-on: [ubuntu-latest]
    steps:
      - name: Download build_webextension.zip
        uses: actions/download-artifact@v2
        with:
          name: build_webextension.zip
          path: build_webextension
      - name: Download build-wrapped_webextension.zip
        uses: actions/download-artifact@v2
        with:
          name: build-wrapped_webextension.zip
          path: build-wrapped_webextension
      - name: Download build-ubuntu-20_04_webextension.zip
        uses: actions/download-artifact@v2
        with:
          name: build-ubuntu-20_04_webextension.zip
          path: build-ubuntu-20_04_webextension
      - name: Make unpack dirs
        run: mkdir build build-wrapped build-ubuntu-20_04
      - name: Unpack build_webextension.zip
        run: unzip ../build_webextension/arcollect.zip
        working-directory: build
      - name: Unpack build-wrapped_webextension.zip
        run: unzip ../build-wrapped_webextension/arcollect.zip
        working-directory: build-wrapped
      - name: Unpack build-ubuntu-20_04_webextension.zip
        run: unzip ../build-ubuntu-20_04_webextension/arcollect.zip
        working-directory: build-ubuntu-20_04
      - name: Compare build and build-wrapped results
        run: diff -ry build build-wrapped
      - name: Compare build and build-ubuntu-20_04 results
        run: diff -ry build build-ubuntu-20_04
