# Webextension specific CI that sign unlisted versions.

name: Private extension build and signing

on:
  # This actions is manually triggered.
  workflow_dispatch:

jobs:
  build:
    # Simply build the webextension (only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-options: -Denable_native_progs=false # Disable C++ code
      - uses: actions/upload-artifact@v2
        with:
          name: arcollect-webextension.zip
          path: build/webextension/arcollect.zip
  sign-amo:
    # Sign the webextenson
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download arcollect-webextension.zip artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: arcollect-webextension.zip
          path: arcollect-webextension.zip
      - name: Unzip arcollect-webextension.zip
        run: unzip arcollect-webextension.zip -d webextension
      - name: npm install web-ext
        run: npm install --global web-ext
      - name: Perform signing on addons.mozilla.org
        run: web-ext sign --no-input --no-config-discovery --channel unlisted -s webextension -a web-ext-artifacts
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - uses: actions/upload-artifact@v2
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts
