name: Create a new release
on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    name: Regular CI build
    uses: ./.github/workflows/build.yml
  sign-amo:
    # Sign the webextenson
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download arcollect-webextension.zip artifact
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: build-wrapped_webextension.zip
      - name: Unzip arcollect-webextension.zip
        run: unzip arcollect.zip -d webextension
      - name: npm install web-ext
        run: npm install web-ext
      - name: Perform signing on addons.mozilla.org
        run: node ./node_modules/.bin/web-ext sign --no-input --no-config-discovery --channel unlisted -s webextension -a web-ext-artifacts
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_WEB_EXT_API_SECRET }}
      - name: Upload web-ext artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts
  release:
    # Create a new draft release
    runs-on: ubuntu-latest
    needs: [build, sign-amo]
    steps:
      - name: Checkout repository
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - name: Generate PKGBUILD for GitHub releases
        run: sh generate-PKGBUILD.sh release-ci > ../PKGBUILD
        working-directory: packaging
      - name: Download AMO signed webextension
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts
      - name: Download ArchLinux (x86_64) package
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: archlinux-x86_64-package
          path: archlinux-x86_64-package
      - name: Download Ubuntu 22.04 (amd64) package
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ubuntu-22_04-amd64-package
      - name: Download Windows x64 MSI
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: windows-2019-x64-package
      - name: Rename Windows x64 MSI
        run: mv arcollect.msi arcollect-${{ github.ref_name }}-x64.msi
      - name: Draft release body # TODO Also autogenerate title
        run: git log --format=%B -n 1 | tail -n +3 | cut -f 2- > release.body
        shell: bash
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: release.body
          files: |
            web-ext-artifacts/*
            PKGBUILD
            archlinux-x86_64-package/arcollect-*
            arcollect-*.msi
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
