name: Create a new release
on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    name: Regular CI build
    uses: ./.github/workflows/build.yml
  sign-amo:
    # Sign the webextenson
    name: Signing on AMO (Firefox)
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download arcollect-webextension.zip artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: build-wrapped_webextension.zip
      - name: Unzip arcollect-webextension.zip
        run: unzip arcollect.zip -d webextension
      - name: npm install web-ext
        run: npm install web-ext
      - name: Perform signing on addons.mozilla.org
        run: node ./node_modules/.bin/web-ext sign --no-input --no-config-discovery --channel unlisted -s webextension -a web-ext-artifacts
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_WEB_EXT_API_SECRET }}
      - name: Upload web-ext artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts
  release:
    # Create a new draft release
    name: Perform GitHub release
    runs-on: ubuntu-latest
    needs: [build, sign-amo]
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Generate PKGBUILD for GitHub releases
        run: sh generate-PKGBUILD.sh release-ci > ../PKGBUILD
        working-directory: packaging
      - name: Download AMO signed webextension
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: web-ext-artifacts
          path: web-ext-artifacts
      - name: Download ArchLinux (x86_64) package
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: archlinux-x86_64-package
          path: archlinux-x86_64-package
      - name: Download Ubuntu 22.04 (amd64) package
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: ubuntu-22_04-amd64-package
      - name: Download Ubuntu 20.04 (amd64) package
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: ubuntu-20_04-amd64-package
      - name: Download Windows x64 MSI
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: windows-2019-x64-package
      - name: Draft release body # TODO Also autogenerate title
        run: git log --format=%B -n 1 | tail -n +3 | cut -f 2- > release.body
        shell: bash
      - name: Release on GitHub
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          draft: true
          body_path: release.body
          files: |
            web-ext-artifacts/*
            PKGBUILD
            archlinux-x86_64-package/arcollect-*
            arcollect-*.msi
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
